version: '3'
services:
  inmemory-manager-inmemory-manager-frontend:
    image: ubuntu-pc:50102/inmemory-manager/inmemory-manager-frontend
    build: .
    container_name: inmemory-manager-inmemory-manager-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inmemory-manager-inmemory-manager-frontend-secure.rule=Host(`ubuntu-pc`) && PathPrefix(`/inmemory-manager/inmemory-manager-frontend`)"
networks:
  default:
    name: docker_network