server {
    listen 80;
    server_name localhost;

    location /inmemory-manager/inmemory-manager-frontend/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /inmemory-manager/inmemory-manager-frontend/index.html;
    }

    location = /inmemory-manager/inmemory-manager-frontend {
        return 301 /inmemory-manager/inmemory-manager-frontend/;
    }

    location /inmemory-manager/inmemory-manager-service/api/ {
        resolver 127.0.0.11 valid=30s;
        set $backend_upstream http://inmemory-manager-inmemory-manager-service-backend:8080;
        proxy_pass $backend_upstream/inmemory-manager/inmemory-manager-service/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
