server:
  port: 8080
  servlet:
    context-path: /inmemory-manager/inmemory-manager-service

spring:
  application:
    name: inmemory-manager-service
  config:
    import: optional:nacos:
  cloud:
    nacos:
      discovery:
        server-addr: 10.126.126.2:8848
        namespace: public
      config:
        server-addr: 10.126.126.2:8848
        namespace: public
        file-extension: yml

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html